const modelPlace={11:'琵琶湖'};let models=[],predictionMode='hit';
function interp(x,xs,ys){if(x<=xs[0])return ys[0];let h=xs.length-1;if(x>=xs[h])return ys[h];let l=0,r=h;while(r-l>1){let m=(l+r)>>1;if(xs[m]<=x)l=m;else r=m}let den=xs[r]-xs[l];return den?ys[l]+(x-xs[l])/den*(ys[r]-ys[l]):ys[l]}
function raw(m,a){let s=m.baseline;for(const t of m.trees){let i=0,guard=0;while(!t[i][5]){if(++guard>1000)throw new Error('V8 tree loop');const z=t[i],v=a[z[0]];i=Number.isNaN(v)?(z[4]?z[2]:z[3]):(v<=z[1]?z[2]:z[3])}s+=t[i][6]}return 1/(1+Math.exp(-s))}
function rankValue(v){if(typeof v==='number')return v;const s=String(v||'').toUpperCase();return s==='A1'?3:s==='A2'?4:s==='B1'?1:s==='B2'?2:Number(v)}
function featureArray(m,r,k,x){let ds=String(r.date||day().replace(/(....)(..)(..)/,'$1-$2-$3')),dt=new Date(ds+'T00:00:00+09:00'),month=dt.getMonth()+1,dow=(dt.getDay()+6)%7;let place=modelPlace[sid]||N[sid]||'',ci=m.place_categories.indexOf(place);let vals=[Number(rno),month,dow,Number(k),Number(x.age),Number(x.weight),Number(x.average_start_timing),rankValue(x.rank_number),Number(x.late_count),Number(x.flying_count),Number(x.national_win_rate),Number(x.national_top_2_percent),Number(x.local_win_rate),Number(x.local_top_2_percent),Number(x.motor_top_2_percent),Number(x.motor_top_3_percent),Number(x.boat_top_2_percent),Number(x.boat_top_3_percent)];return [ci,...vals.map((v,i)=>Number.isFinite(v)?v:m.num_medians[i])]}
function probs(r,k,x){return models.map(m=>{let p=interp(raw(m,featureArray(m,r,k,x)),m.cal_x,m.cal_y);return Math.max(1e-6,Math.min(.999999,p))})}
function v8HtmlP(p){return `V8 1着 <b>${(p[0]*100).toFixed(1)}%</b><br>2着 ${(p[1]*100).toFixed(1)}%｜3着 ${(p[2]*100).toFixed(1)}%`}
function motorFactors(rows,b=.08){let a=rows.map(z=>(Number(z.x.motor_top_2_percent)+Number(z.x.motor_top_3_percent))/2),good=a.filter(v=>Number.isFinite(v)&&v>0);if(good.length<2)return a.map(()=>1);let mean=good.reduce((s,v)=>s+v,0)/good.length,sd=Math.sqrt(good.reduce((s,v)=>s+(v-mean)**2,0)/good.length);return a.map(v=>Math.exp(b*(Number.isFinite(v)&&v>0&&sd>1e-9?Math.max(-2,Math.min(2,(v-mean)/sd)):0)))}
function exhibitionScores(r){const rs=Object.entries(r.racers||{}).sort((a,b)=>+a[0]-+b[0]);const out={};rs.forEach(([k])=>out[k]=0);const defs=[['exhibition_time',30],['start_timing',25],['lap_time',20],['turn_time',15],['straight_time',10]];for(const [f,w] of defs){const vals=rs.map(([k])=>{const p=mergeOriginalEx(r,k);return [k,p[f]]}).filter(z=>z[1]!=null&&z[1]!==''&&Number.isFinite(Number(z[1]))&&Number(z[1])>=0).map(z=>[z[0],Number(z[1])]);if(vals.length<2)continue;const a=vals.map(z=>z[1]),hi=Math.max(...a),lo=Math.min(...a);for(const [k,x] of vals)out[k]+=(hi===lo?0.5:(hi-x)/(hi-lo))*w}return out}
function makeBets(rows,max=6,mode=predictionMode){if(!rows.length||rows.some(z=>!z.p))return[];const strength=new Map(rows.slice().sort((a,b)=>weightedV8Total(b.p)-weightedV8Total(a.p)).map((z,i)=>[z.k,i]));let all=[];for(const x of rows)for(const y of rows)for(const z of rows){if(x.k===y.k||x.k===z.k||y.k===z.k)continue;const raw=Math.max(1e-12,x.p[0])*Math.max(1e-12,y.p[1])*Math.max(1e-12,z.p[2]),r1=strength.get(x.k)||0,r2=strength.get(y.k)||0,r3=strength.get(z.k)||0,hole=(r1*.55+r2*.28+r3*.17)/5,returnScore=Math.pow(raw,.68)*(1+hole*1.15);all.push({combo:`${x.k}-${y.k}-${z.k}`,boats:[x.k,y.k,z.k],ranks:[r1,r2,r3],raw,score:mode==='return'?returnScore:raw,hole})}all.sort((a,b)=>b.raw-a.raw);let top;if(mode==='balance'){const pool=all.slice(0,40),chosen=[];while(chosen.length<Math.min(max,pool.length)){let best=null,bestValue=-1;for(const bet of pool){if(chosen.some(c=>c.combo===bet.combo))continue;const base=bet.raw/(pool[0]?.raw||1),novelty=bet.boats.reduce((sum,boat,pos)=>sum+(chosen.some(c=>c.boats[pos]===boat)?0:[.55,.3,.15][pos]),0),value=base*.58+novelty*.42;if(value>bestValue){bestValue=value;best=bet}}if(!best)break;chosen.push({...best,score:bestValue})}top=chosen}else if(mode==='return'){const bestRaw=all[0]?.raw||1,valuePool=all.filter(b=>b.raw>=bestRaw*.08&&b.hole>=.1).sort((a,b)=>b.score-a.score),outsiders=valuePool.filter(b=>b.ranks[0]>=1).slice(0,Math.ceil(max*.67)),favoriteHoles=valuePool.filter(b=>b.ranks[0]===0&&!outsiders.some(x=>x.combo===b.combo)).slice(0,max-outsiders.length);top=[...outsiders,...favoriteHoles].sort((a,b)=>b.score-a.score);if(top.length<max)top.push(...valuePool.filter(b=>!top.some(x=>x.combo===b.combo)).slice(0,max-top.length))}else top=all.slice(0,max);const sum=top.reduce((t,b)=>t+b.score,0)||1;return top.map((b,i)=>({...b,share:b.score/sum,rank:i+1}))}
function renderBets(rows){const el=document.getElementById('bets');if(models.length!==3){el.textContent='V8モデル待機中';return}const picks=makeBets(rows,6,predictionMode);if(!picks.length){el.textContent='買い目を計算できません';return}const notes={hit:'確率上位を優先して的中を狙います',balance:'本命を残しながら着順の組み合わせを分散します',return:'V8評価内の穴度を加味します（オッズ未反映）'};el.innerHTML=`<div class="modehint">${notes[predictionMode]}</div><table class="bettable"><thead><tr><th>順</th><th>組番</th><th>モード指数</th></tr></thead><tbody>${picks.map(b=>`<tr><td>${b.rank}</td><td>${b.combo}</td><td>${(b.share*100).toFixed(1)}%</td></tr>`).join('')}</tbody></table>`}
function resultStoreKey(){return `kyotei_v8_dev_result_${day()}_${String(sid).padStart(2,'0')}_${String(rno).padStart(2,'0')}`}
function hasOfficialResult(r){if(r?.result?.payouts?.trifecta?.[0])return true;const racers=Array.isArray(r?.result?.racers)?r.result.racers:Object.values(r?.result?.racers||{});return racers.some(x=>x?.place_number!=null&&x.place_number!=='')}
function savePredictionSnapshot(r,rows){if(models.length!==3||!rows.length||rows.some(z=>!z.p)||hasOfficialResult(r))return false;const close=typeof raceCloseMs==='function'?raceCloseMs(r):NaN;if(Number.isFinite(close)&&close<=Date.now())return false;const allModes={};for(const mode of ['hit','balance','return']){const picks=makeBets(rows,6,mode);if(picks.length)allModes[mode]={picks:picks.map(b=>b.combo),stake:picks.length*100,settled:false,hit:false,payout:0}}const selected=allModes[predictionMode];if(!selected)return false;const key=resultStoreKey(),prev=JSON.parse(localStorage.getItem(key)||'null');if(prev?.settled)return false;const rec={date:day(),stadium:String(sid),stadium_name:N[sid]||String(sid),race:String(rno),mode:predictionMode,modes:allModes,picks:selected.picks,stake:selected.stake,settled:false,hit:false,payout:0,probabilities:Object.fromEntries(rows.map(z=>[z.k,z.p.map(Number)])),saved_at:new Date().toISOString(),auto_saved:true};try{localStorage.setItem(key,JSON.stringify(rec));return true}catch(e){return false}}
function settlePredictionKey(r,key){const t=r?.result?.payouts?.trifecta?.[0];if(!t)return false;let rec;try{rec=JSON.parse(localStorage.getItem(key)||'null')}catch(e){return false}if(!rec||rec.settled)return false;const combo=String(t.combination||'').trim(),amount=Number(t.amount||0);if(rec.modes&&typeof rec.modes==='object'){for(const mode of ['hit','balance','return']){const m=rec.modes[mode];if(!m)continue;m.settled=true;m.result=combo;m.hit=Array.isArray(m.picks)&&m.picks.includes(combo);m.payout=m.hit?amount:0}const selected=rec.modes[rec.mode]||rec.modes.hit;rec.hit=!!selected?.hit;rec.payout=Number(selected?.payout||0);rec.picks=selected?.picks||rec.picks;rec.stake=Number(selected?.stake||rec.stake||0)}else{rec.hit=Array.isArray(rec.picks)&&rec.picks.includes(combo);rec.payout=rec.hit?amount:0}rec.settled=true;rec.result=combo;rec.settled_at=new Date().toISOString();try{localStorage.setItem(key,JSON.stringify(rec));return true}catch(e){return false}}
function settlePrediction(r){return settlePredictionKey(r,resultStoreKey())}
function settleStoredPredictions(data,date){const prefix=`kyotei_v8_dev_result_${date}_`,keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(prefix))keys.push(key)}let saved=0,settled=0,pending=0;for(const key of keys){let rec;try{rec=JSON.parse(localStorage.getItem(key)||'null')}catch(e){continue}if(!rec||rec.settled)continue;saved++;const stadium=String(rec.stadium||''),raceNo=String(Number(rec.race||0)),race=data?.programs?.stadiums?.[stadium]?.races?.[raceNo];if(race?.result?.payouts?.trifecta?.[0]){if(settlePredictionKey(race,key))settled++}else pending++}renderStats();return{saved,settled,pending}}
function renderModeStats(records){
  const el=document.getElementById('modeStats');if(!el)return;
  const sums={hit:{races:0,hits:0,invest:0,payout:0},balance:{races:0,hits:0,invest:0,payout:0},return:{races:0,hits:0,invest:0,payout:0}};
  for(const x of records){
    if(x?.modes&&typeof x.modes==='object'){
      for(const mode of Object.keys(sums)){
        const m=x.modes[mode];if(!m?.settled)continue;
        sums[mode].races++;if(m.hit)sums[mode].hits++;
        sums[mode].invest+=Number(m.stake||0);sums[mode].payout+=Number(m.payout||0)
      }
    }else if(x?.settled){
      const mode=sums[x.mode]?x.mode:'hit';sums[mode].races++;if(x.hit)sums[mode].hits++;
      sums[mode].invest+=Number(x.stake||0);sums[mode].payout+=Number(x.payout||0)
    }
  }
  const labels={hit:'的中重視',balance:'バランス',return:'回収重視'};
  const cards=Object.entries(sums).map(([mode,s])=>{
    const hitRate=s.races?(s.hits/s.races*100).toFixed(1)+'%':'--',roi=s.invest?(s.payout/s.invest*100).toFixed(1)+'%':'--';
    return `<div class="modestat ${mode===predictionMode?'active':''}"><small class="mode-name">${labels[mode]}</small><div class="mode-metrics"><div><span>的中率</span><b>${hitRate}</b></div><div><span>回収率</span><b class="mode-roi">${roi}</b></div></div><div class="mode-money"><span><em>投資</em><strong>¥${s.invest.toLocaleString()}</strong></span><span><em>払戻</em><strong>¥${s.payout.toLocaleString()}</strong></span></div><span class="mode-count">的中 ${s.hits}/${s.races}R</span></div>`
  }).join('');
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';');
  const selected=records.find(x=>String(x?.date||'')===String(day())&&Number(x?.stadium)===Number(sid)&&Number(x?.race)===Number(rno));
  const date=String(day()).replace(/^(\d{4})(\d{2})(\d{2})$/,'$1/$2/$3');
  const venue=N?.[sid]||selected?.stadium_name||sid||'--';
  const race=Number(rno)||rno||'--';
  let audit;
  if(!selected){
    audit=`<div class="modeaudit"><div class="audit-title"><span>選択中のレース</span><b>${safe(date)} ${safe(venue)} ${safe(race)}R</b></div><div class="audit-empty-note">このレースは、締切前に保存された買い目がありません。</div></div>`
  }else{
    const modeData=selected.modes&&typeof selected.modes==='object'?selected.modes:{[selected.mode||'hit']:{picks:selected.picks,settled:selected.settled,hit:selected.hit,result:selected.result}};
    const result=String(selected.result||Object.values(modeData).find(m=>m?.result)?.result||'').trim();
    const settled=!!selected.settled||Object.values(modeData).some(m=>m?.settled);
    const rows=Object.keys(labels).map(mode=>{
      const m=modeData[mode],picks=Array.isArray(m?.picks)?m.picks:[];
      const pickHtml=picks.length?picks.map(p=>`<span class="${result&&String(p)===result?'winner':''}">${safe(p)}</span>`).join(''):'<span class="no-picks">記録なし</span>';
      const status=!m?'<span class="audit-status">記録なし</span>':m.settled?(m.hit?'<span class="audit-status hit">的中</span>':'<span class="audit-status miss">不的中</span>'):'<span class="audit-status wait">判定待ち</span>';
      return `<div class="audit-row"><div class="audit-mode"><b>${labels[mode]}</b>${status}</div><div class="audit-picks">${pickHtml}</div></div>`
    }).join('');
    audit=`<div class="modeaudit"><div class="audit-title"><span>選択中のレース</span><b>${safe(date)} ${safe(venue)} ${safe(race)}R</b></div><div class="audit-result">結果 <strong>${safe(settled?(result||'--'):'未確定')}</strong></div><div class="audit-label">保存された買い目</div>${rows}</div>`
  }
  el.innerHTML=cards+audit
}
function renderStats(){let races=0,hits=0,invest=0,payout=0,records=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!k.startsWith('kyotei_v8_dev_result_'))continue;let x;try{x=JSON.parse(localStorage.getItem(k)||'null')}catch(e){continue}if(x)records.push(x);if(!x?.settled)continue;races++;if(x.hit)hits++;invest+=Number(x.stake||0);payout+=Number(x.payout||0)}const vals=document.querySelectorAll('.stats .stat b');if(vals.length>=6){const hitRate=races?hits/races*100:0,roi=invest?payout/invest*100:0,profit=payout-invest;vals[0].textContent=races?hitRate.toFixed(1)+'%':'--';vals[1].textContent=races?roi.toFixed(1)+'%':'--';vals[2].textContent=races+'R';vals[3].textContent='¥'+invest.toLocaleString();vals[4].textContent='¥'+payout.toLocaleString();vals[5].textContent=(profit<0?'-¥':'¥')+Math.abs(profit).toLocaleString()}renderModeStats(records)}
function transferRecords(){const records={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key||!key.startsWith('kyotei_v8_dev_result_'))continue;const value=localStorage.getItem(key);if(value!=null)records[key]=value}return records}
function setTransferStatus(message,type=''){const el=document.getElementById('transferStatus');if(!el)return;el.textContent=message;el.className='transferStatus'+(type?' '+type:'')}
function exportTransferData(){try{const records=transferRecords(),payload={schema:'kyotei-v8-results',version:1,exportedAt:new Date().toISOString(),recordCount:Object.keys(records).length,records},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a'),d=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Tokyo'});a.href=url;a.download=`kyotei-v8-results-${d}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setTransferStatus(`${payload.recordCount}件の実績データを書き出しました。`,'ok')}catch(e){setTransferStatus('書き出しに失敗しました：'+e.message,'err')}}
async function importTransferData(file){try{if(!file)throw new Error('ファイルが選択されていません');const payload=JSON.parse(await file.text());if(payload?.schema!=='kyotei-v8-results'||payload?.version!==1||!payload.records||Array.isArray(payload.records))throw new Error('この競艇AI用のデータではありません');const entries=Object.entries(payload.records).filter(([k,v])=>k.startsWith('kyotei_v8_dev_result_')&&typeof v==='string'),validated=entries.map(([key,value])=>{JSON.parse(value);return[key,value]});for(const [key,value] of validated)localStorage.setItem(key,value);renderStats();if(typeof draw==='function'&&D&&sid)draw();setTransferStatus(`${validated.length}件の実績データを読み込みました。`,'ok')}catch(e){setTransferStatus('読み込みに失敗しました：'+e.message,'err')}finally{const input=document.getElementById('importDataFile');if(input)input.value=''}}
function setupTransfer(){const exportBtn=document.getElementById('exportDataBtn'),importBtn=document.getElementById('importDataBtn'),input=document.getElementById('importDataFile');if(!exportBtn||!importBtn||!input)return;exportBtn.onclick=exportTransferData;importBtn.onclick=()=>input.click();input.onchange=()=>importTransferData(input.files?.[0])}
function exhibitionFactors(r,rows){const sc=exhibitionScores(r),vals=rows.map(z=>sc[z.k]).filter(Number.isFinite);if(vals.length<2)return rows.map(()=>1);const avg=vals.reduce((a,b)=>a+b,0)/vals.length;return rows.map(z=>{const v=sc[z.k];return Number.isFinite(v)?Math.max(.94,Math.min(1.06,1+(v-avg)*.002)):1})}
function weightedV8Total(p){return Array.isArray(p)&&p.length>=3?p[0]*.5+p[1]*.3+p[2]*.2:NaN}
function raceRelativeScores(values){const usable=values.filter(Number.isFinite),max=usable.length?Math.max(...usable):0;if(max<=0)return values.map(()=>0);return values.map(v=>Number.isFinite(v)?Math.max(0,Math.min(100,v/max*100)):0)}
function componentScores(values){const usable=values.filter(Number.isFinite);if(usable.length<2)return values.map(v=>Number.isFinite(v)?50:null);const lo=Math.min(...usable),hi=Math.max(...usable);if(hi-lo<1e-9)return values.map(v=>Number.isFinite(v)?50:null);return values.map(v=>Number.isFinite(v)?Math.max(0,Math.min(100,(v-lo)/(hi-lo)*100)):null)}
function v8ScoreDetails(r,rows,exs){
  const baseRaw=rows.map(({k,x,p})=>{try{const base=typeof baseV8Probs==='function'?baseV8Probs(r,k,x):p;return weightedV8Total(base)}catch(e){return weightedV8Total(p)}});
  const courseRaw=rows.map(({k,x})=>{if(typeof racerCourseStat!=='function')return NaN;const s=racerCourseStat(r,k,x);if(!s)return NaN;const rates=[Number(s.win1),Number(s.win2),Number(s.win3)],avgStart=Number(s.avgStart);if(!rates.some(Number.isFinite))return NaN;return (Number.isFinite(rates[0])?rates[0]:0)*.5+(Number.isFinite(rates[1])?rates[1]:0)*.3+(Number.isFinite(rates[2])?rates[2]:0)*.2-(Number.isFinite(avgStart)?avgStart*10:0)});
  const motorRaw=rows.map(({x})=>{const vals=[[x.motor_top_2_percent,.35],[x.motor_top_3_percent,.25],[x.boat_top_2_percent,.22],[x.boat_top_3_percent,.18]].map(([v,w])=>[Number(v),w]).filter(([v])=>Number.isFinite(v)&&v>0);const den=vals.reduce((s,[,w])=>s+w,0);return den?vals.reduce((s,[v,w])=>s+v*w,0)/den:NaN});
  const exhibitRaw=rows.map(({k})=>{const p=typeof mergeOriginalEx==='function'?mergeOriginalEx(r,k):{},has=['exhibition_time','start_timing','lap_time','turn_time','straight_time'].some(f=>p?.[f]!=null&&p[f]!==''&&Number.isFinite(Number(p[f]))&&Number(p[f])>=0);return has?Number(exs?.[k]):NaN});
  const venueRaw=rows.map(({k})=>typeof venueScoreForLane==='function'?venueScoreForLane(r,k):NaN),techniqueRaw=rows.map(({k,x})=>typeof techniqueBoatSignal==='function'?Number(techniqueBoatSignal(r,k,x)?.score):NaN),overall=raceRelativeScores(rows.map(z=>weightedV8Total(z.p))),base=componentScores(baseRaw),course=componentScores(courseRaw),venue=componentScores(venueRaw),motor=componentScores(motorRaw),exhibition=componentScores(exhibitRaw),technique=componentScores(techniqueRaw);
  return rows.map((z,i)=>{const x=z.x,preview=typeof mergeOriginalEx==='function'?mergeOriginalEx(r,z.k):{},baseFields=[x.age,x.weight,x.average_start_timing,x.rank_number,x.flying_count,x.late_count,x.national_win_rate,x.national_top_2_percent,x.local_win_rate,x.local_top_2_percent],baseCoverage=baseFields.filter(v=>v!=null&&v!==''&&Number.isFinite(Number(v))||String(v||'').match(/^[AB][12]$/i)).length/baseFields.length,motorFields=[x.motor_top_2_percent,x.motor_top_3_percent,x.boat_top_2_percent,x.boat_top_3_percent],motorCoverage=motorFields.filter(v=>v!=null&&v!==''&&Number.isFinite(Number(v))&&Number(v)>0).length/motorFields.length,exFields=['exhibition_time','start_timing','lap_time','turn_time','straight_time'],exCoverage=exFields.filter(f=>preview?.[f]!=null&&preview[f]!==''&&Number.isFinite(Number(preview[f]))&&Number(preview[f])>=0).length/exFields.length,courseCoverage=Number.isFinite(courseRaw[i])?1:0,venueCoverage=Number.isFinite(venueRaw[i])?1:0,techniqueCoverage=Number.isFinite(techniqueRaw[i])?1:0,coverage=Math.round(baseCoverage*30+courseCoverage*18+venueCoverage*10+motorCoverage*14+exCoverage*18+techniqueCoverage*10),grade=coverage>=85?'A':coverage>=65?'B':'C';return{score:overall[i],grade,coverage,base:base[i],course:course[i],venue:venue[i],motor:motor[i],exhibition:exhibition[i],technique:technique[i]}})}
