(function(){
const P='kyotei_v8_dev_result_',M=['hit','balance','return'],L={hit:'的中重視',balance:'バランス',return:'回収重視'};
const yen=n=>(Number(n||0)<0?'-¥':'¥')+Math.abs(Math.round(Number(n||0))).toLocaleString();
function recs(){let a=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(!k?.startsWith(P))continue;try{let r=JSON.parse(localStorage.getItem(k)||'null');if(r)a.push(r)}catch(e){}}return a}
function md(r,m){return r?.modes?.[m]||((r?.mode||'hit')===m&&r?.picks?{picks:r.picks,stake:r.stake,settled:r.settled,hit:r.hit,payout:r.payout}:null)}
function item(r,m,u){let x=md(r,m);if(!x?.settled||!x.picks?.length)return null;let old=Number(x.stake||0)/x.picks.length||100,inv=x.picks.length*u,pay=Number(x.payout||0)*(u/old);return{date:String(r.date||''),inv,pay,profit:pay-inv,hit:!!x.hit}}
function sum(a){a=a.filter(Boolean).sort((x,y)=>x.date.localeCompare(y.date));let inv=0,pay=0,h=0,eq=0,peak=0,dd=0;a.forEach(x=>{inv+=x.inv;pay+=x.pay;if(x.hit)h++;eq+=x.profit;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)});return{n:a.length,h,inv,pay,p:pay-inv,roi:inv?pay/inv*100:0,hr:a.length?h/a.length*100:0,dd}}
function ensure(){if(document.getElementById('v8SimulatorPanel'))return;let a=document.getElementById('baseStats')?.closest('.panel');if(!a)return;let p=document.createElement('div');p.className='panel base-view-panel simulator-panel';p.id='v8SimulatorPanel';p.hidden=a.hidden;p.innerHTML='<div class="title">V8 収支シミュレーター</div><div class="sim-controls"><label>買い方<select id="simMode"><option value="hit">的中重視</option><option value="balance">バランス</option><option value="return">回収重視</option></select></label><label>1点<select id="simUnit"><option value="100">100円</option><option value="200">200円</option><option value="500">500円</option><option value="1000">1,000円</option></select></label></div><div class="sim-note">保存済みV8買い目を購入した想定で再計算します。実際の購入は行いません。</div><b>今日</b><div class="sim-grid" id="simToday"></div><b>累積</b><div class="sim-grid" id="simAll"></div><div class="sim-foot" id="simFoot"></div>';a.insertAdjacentElement('afterend',p);let m=document.getElementById('simMode'),u=document.getElementById('simUnit');m.value=localStorage.getItem('kyotei_v8_sim_mode')||'hit';u.value=localStorage.getItem('kyotei_v8_sim_unit')||'100';m.onchange=()=>{localStorage.setItem('kyotei_v8_sim_mode',m.value);render()};u.onchange=()=>{localStorage.setItem('kyotei_v8_sim_unit',u.value);render()}}
function html(s){return [['集計',s.n+'R'],['的中率',s.n?s.hr.toFixed(1)+'%':'--'],['投資',yen(s.inv)],['払戻',yen(s.pay)],['回収率',s.inv?s.roi.toFixed(1)+'%':'--'],['収支',yen(s.p)],['最大DD',yen(s.dd)]].map(x=>'<div><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('')}
function render(){ensure();let p=document.getElementById('v8SimulatorPanel');if(!p)return;let base=document.getElementById('baseStats')?.closest('.panel');p.hidden=base?base.hidden:false;let m=document.getElementById('simMode')?.value||'hit',u=Number(document.getElementById('simUnit')?.value||100),all=recs().map(r=>item(r,m,u)).filter(Boolean),d=typeof day==='function'?String(day()):new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Tokyo'}).replaceAll('-','');document.getElementById('simToday').innerHTML=html(sum(all.filter(x=>x.date===d)));document.getElementById('simAll').innerHTML=html(sum(all));document.getElementById('simFoot').textContent=L[m]+'｜1点 '+yen(u)+'｜確定済みV8記録のみ集計'}
ensure();let old=typeof renderStats==='function'?renderStats:null;if(old)renderStats=function(){old();render()};document.querySelectorAll('.prediction-type-tabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(render,0)));window.renderV8Simulator=render;render();
})();