import fs from 'node:fs';
import path from 'node:path';
import {summarizeExperts} from './expert_summary.mjs';

const ROOT=path.resolve(import.meta.dirname,'..');
const CURRENT=path.join(ROOT,'dev/server-predictions.json');
const ARCHIVE_DIR=path.join(ROOT,'dev/server-predictions-archive');
const MODES=['hit','balance','return'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const jsonFile=(file,fallback={})=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}};

async function getJson(url){const res=await fetch(url,{headers:{'user-agent':'kyotei-v8-expert-backfill'}});if(!res.ok)throw Error(`${url}: HTTP ${res.status}`);return res.json()}
async function getText(url){try{const res=await fetch(url,{headers:{'user-agent':'kyotei-v8-expert-backfill'}});return res.ok?await res.text():''}catch{return''}}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows}
function applyOriginalExhibition(program,text,date){const rows=parseCsv(text);if(rows.length<2)return 0;const head=rows[0],idx=Object.fromEntries(head.map((h,i)=>[String(h).replace(/^\ufeff/,''),i]));if(idx['レースコード']==null)return 0;let count=0;for(const row of rows.slice(1)){const code=String(row[idx['レースコード']]||'').trim();if(!code.startsWith(date)||code.length<12)continue;const sid=String(Number(code.slice(8,10))),raceNo=String(Number(code.slice(10,12))),race=program?.programs?.stadiums?.[sid]?.races?.[raceNo];if(!race)continue;const labels=[1,2,3].map(n=>row[idx[`計測項目${n}`]]||'');race.preview=race.preview||{};race.preview.racers=race.preview.racers||{};for(let lane=1;lane<=6;lane++){const target=race.preview.racers[String(lane)]=race.preview.racers[String(lane)]||{};for(let n=1;n<=3;n++){const label=String(labels[n-1]||'').replace(/\s+/g,''),value=Number(row[idx[`艇${lane}_値${n}`]]);if(!Number.isFinite(value))continue;if(/一周|1周|半周|ラップ/.test(label))target.lap_time=value;else if(/まわり|回り|ターン/.test(label))target.turn_time=value;else if(/直線/.test(label))target.straight_time=value}}count++}return count}
function preview(r,lane){return r?.preview?.racers?.[String(lane)]||{}}
function exhibitionScores(r){const rs=Object.entries(r.racers||{}).sort((a,b)=>+a[0]-+b[0]),out={};rs.forEach(([k])=>out[k]=0);for(const[f,w]of[['exhibition_time',30],['start_timing',25],['lap_time',20],['turn_time',15],['straight_time',10]]){const vals=rs.map(([k])=>[k,preview(r,k)?.[f]]).filter(z=>z[1]!=null&&z[1]!==''&&Number.isFinite(Number(z[1]))&&Number(z[1])>=0).map(z=>[z[0],Number(z[1])]);if(vals.length<2)continue;const a=vals.map(z=>z[1]),hi=Math.max(...a),lo=Math.min(...a);for(const[k,x]of vals)out[k]+=(hi===lo?.5:(hi-x)/(hi-lo))*w}return out}
function expertAssessment(r,rows){const num=v=>Number.isFinite(Number(v))?Number(v):NaN,one=rows.find(z=>String(z.k)==='1'),others=rows.filter(z=>String(z.k)!=='1'),win=x=>num(x?.x?.national_win_rate),local=x=>num(x?.x?.local_win_rate),st=x=>num(x?.x?.average_start_timing),motor=x=>num(x?.x?.motor_top_2_percent),avg=(arr,f)=>{const a=arr.map(f).filter(Number.isFinite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:NaN},diff=(f,sign=1)=>{const a=f(one),b=avg(others,f);return Number.isFinite(a)&&Number.isFinite(b)?(a-b)*sign:0},dWin=diff(win),dLocal=diff(local),dSt=diff(st,-1)*10,dMotor=diff(motor)/10,inside=clamp(50+dWin*10+dLocal*5+dSt*4+dMotor*4,0,100),ex=exhibitionScores(r),vals=Object.values(ex).map(Number).filter(Number.isFinite),exSpread=vals.length>=2?Math.max(...vals)-Math.min(...vals):0,exhibition=clamp(exSpread*1.4,0,100),p=r?.preview||{},wind=num(p.wind_speed),wave=num(p.wave_height),water=clamp((Number.isFinite(wind)?wind*12:0)+(Number.isFinite(wave)?wave*3:0),0,100),upset=clamp(100-inside*.78+Math.max(0,exhibition-45)*.28+Math.max(0,water-45)*.25,0,100),weights={normal:30,inside,upset:upset*.8,exhibition:exhibition*.65,water:water*.7},sum=Object.values(weights).reduce((a,b)=>a+b,0)||1,labels={normal:'通常',inside:'イン逃げ',upset:'イン崩れ・穴',exhibition:'展示変化',water:'水面'};for(const k of Object.keys(weights))weights[k]/=sum;const active=Object.entries(weights).sort((a,b)=>b[1]-a[1])[0],previewRows=rows.map(z=>preview(r,z.k)),exFields=previewRows.reduce((n,x)=>n+['exhibition_time','start_timing','lap_time','turn_time','straight_time'].filter(f=>x?.[f]!=null&&x[f]!==''&&Number.isFinite(Number(x[f]))).length,0),hasWater=Number.isFinite(wind)&&Number.isFinite(wave),quality=exFields>=24&&hasWater?'full':exFields>=6||hasWater?'partial':'basic';return{version:1,active:active[0],label:labels[active[0]],weights,scores:{inside,upset,exhibition,water},signals:{winDiff:dWin,localDiff:dLocal,startEdge:dSt,motorDiff:dMotor,wind:Number.isFinite(wind)?wind:null,wave:Number.isFinite(wave)?wave:null},reconstructed:true,reconstruction_quality:quality,reconstructed_at:new Date().toISOString()}}
function modeResult(group){return Object.fromEntries(Object.entries(group||{}).map(([mode,m])=>[mode,{hit:!!m?.hit,stake:Number(m?.stake||0),payout:Number(m?.payout||0)}]))}
function expertResult(rec){const combo=String(rec.result||'').trim();if(!combo||!rec.expert_snapshot)return null;return{active:rec.expert_snapshot.active,label:rec.expert_snapshot.label,result:combo,winner:String(combo.split('-')[0]||''),inside_won:String(combo.split('-')[0]||'')==='1',modes:modeResult(rec.modes),value_modes:modeResult(rec.value_modes),settled_at:rec.settled_at||new Date().toISOString(),reconstructed:true}}

export async function run(){
  const files=[CURRENT,...fs.readdirSync(ARCHIVE_DIR).filter(name=>/^\d{6}\.json$/.test(name)).map(name=>path.join(ARCHIVE_DIR,name))],payloads=files.map(file=>({file,payload:jsonFile(file,{records:{}})})),missing=[];
  for(const item of payloads)for(const[key,rec]of Object.entries(item.payload.records||{}))if(rec?.settled&&!rec.cancelled&&!rec.expert_snapshot&&/^\d{8}$/.test(String(rec.date||'')))missing.push({item,key,rec});
  if(!missing.length){console.log(JSON.stringify({targets:0,restored:0,failed:0,status:'already complete'}));return{restored:0,failed:0,summary:payloads[0]?.payload?.expert_summary||null}}
  const dates=[...new Set(missing.map(x=>String(x.rec.date)))].sort();let restored=0,failed=0;
  for(const date of dates){const year=date.slice(0,4),program=await getJson(`https://boatraceopenapi.github.io/api/v1/${year}/${date}.json`),csv=await getText(`https://boatracecsv.github.io/data/previews/original_exhibition/${year}/${date.slice(4,6)}/${date.slice(6,8)}.csv`);applyOriginalExhibition(program,csv,date);for(const x of missing.filter(z=>String(z.rec.date)===date)){const race=program?.programs?.stadiums?.[String(Number(x.rec.stadium))]?.races?.[String(Number(x.rec.race))],rows=Object.entries(race?.racers||{}).sort((a,b)=>+a[0]-+b[0]).map(([k,racer])=>({k:String(k),x:racer}));if(rows.length!==6){failed++;continue}x.rec.expert_snapshot=expertAssessment(race,rows);x.rec.expert_result=expertResult(x.rec);restored++}}
  const all=payloads.flatMap(x=>Object.values(x.payload.records||{})),summary=summarizeExperts(all),now=new Date().toISOString();
  for(const item of payloads){item.payload.updated_at=now;if(item.file===CURRENT)item.payload.expert_summary=summary;else item.payload.expert_summary=summarizeExperts(Object.values(item.payload.records||{}));fs.writeFileSync(item.file,JSON.stringify(item.payload))}
  console.log(JSON.stringify({dates,targets:missing.length,restored,failed,expert_summary:summary}));return{restored,failed,summary}
}

async function selfTest(){const race={racers:Object.fromEntries([1,2,3,4,5,6].map(k=>[k,{national_win_rate:k===1?7:5,local_win_rate:k===1?7:5,average_start_timing:k===1?.12:.18,motor_top_2_percent:k===1?45:30}])),preview:{wind_speed:2,wave_height:2,racers:{}}},snap=expertAssessment(race,Object.entries(race.racers).map(([k,x])=>({k,x}))),rec={result:'1-2-3',settled:true,settled_at:new Date().toISOString(),modes:{hit:{hit:true,stake:600,payout:900}},value_modes:{hit:{hit:true,stake:300,payout:2700}},expert_snapshot:snap};rec.expert_result=expertResult(rec);const summary=summarizeExperts([rec]);if(!snap.active||snap.reconstruction_quality!=='partial'||summary.saved!==1||summary.settled!==1||summary.reconstructed!==1)throw Error('expert backfill self test failed');console.log('expert backfill self-test OK')}
if(import.meta.url===`file://${process.argv[1]}`){if(process.argv.includes('--self-test'))await selfTest();else await run()}
