const raw=a=>{const n=Number(a?.[1]||0),sn=Number(a?.[6]||0),st=sn?Number(a[7])/sn:.17,variance=sn?Math.max(0,Number(a[8])/sn-st*st):0;return{win:n?Number(a[2])/n:1/6,top2:n?Number(a[3])/n:2/6,top3:n?Number(a[4])/n:.5,finish:n?Number(a[5])/n:3.5,st,st_std:Math.sqrt(variance)}};
const smooth=(a,prior,alpha)=>{a=a||[];const n=Number(a[1]||0),sn=Number(a[6]||0),r=raw(a);return{win:(Number(a[2]||0)+alpha*prior.win)/(n+alpha),top2:(Number(a[3]||0)+alpha*prior.top2)/(n+alpha),top3:(Number(a[4]||0)+alpha*prior.top3)/(n+alpha),finish:(Number(a[5]||0)+alpha*prior.finish)/(n+alpha),st:(Number(a[7]||0)+alpha*prior.st)/(sn+alpha),st_std:r.st_std}};

export function aptitudeFeatures(data,racerId,venue,course){
  const racer=data?.racers?.[String(racerId||'')],key=String(Number(course));
  if(!racer||!key)return{};
  const global=raw(data.global_course?.[key]),overall=smooth(racer.o,global,30),courseStats=racer.c?.[key]||[],courseValue=smooth(courseStats,overall,16),venueStats=racer.v?.[venue]||[],venueValue=smooth(venueStats,overall,16),combinedStats=racer.x?.[`${venue}:${key}`]||[],combinedPrior={win:(courseValue.win+venueValue.win)/2,top2:(courseValue.top2+venueValue.top2)/2,top3:(courseValue.top3+venueValue.top3)/2,finish:(courseValue.finish+venueValue.finish)/2,st:(courseValue.st+venueValue.st)/2},combined=smooth(combinedStats,combinedPrior,10),selected=Number(combinedStats[1]||0)>=8?combined:Number(courseStats[1]||0)>=12?courseValue:Number(venueStats[1]||0)>=12?venueValue:overall;
  return{APT_STARTS:Number(racer.o?.[0]||0),APT_WIN:overall.win,APT_TOP2:overall.top2,APT_TOP3:overall.top3,APT_MEAN_FINISH:overall.finish,APT_MEAN_ST:overall.st,APT_ST_STD:overall.st_std,APT_COURSE_STARTS:Number(courseStats[0]||0),APT_COURSE_WIN:courseValue.win,APT_COURSE_TOP2:courseValue.top2,APT_COURSE_TOP3:courseValue.top3,APT_COURSE_ST:courseValue.st,APT_VENUE_STARTS:Number(venueStats[0]||0),APT_VENUE_WIN:venueValue.win,APT_VENUE_TOP2:venueValue.top2,APT_VENUE_TOP3:venueValue.top3,APT_VENUE_ST:venueValue.st,APT_VC_STARTS:Number(combinedStats[0]||0),APT_SELECTED_WIN:selected.win,APT_SELECTED_TOP2:selected.top2,APT_SELECTED_TOP3:selected.top3,APT_SELECTED_ST:selected.st,APT_VENUE_COURSE_ADV:selected.win-global.win};
}
