import fs from 'node:fs';
import {normalizeModel,predictionRows,makeBets} from './update_server_predictions.mjs';
const ROOT=new URL('../',import.meta.url).pathname, apt=JSON.parse(fs.readFileSync(ROOT+'racer-aptitude.json','utf8')), model=normalizeModel(JSON.parse(fs.readFileSync(ROOT+'v8_model_aptitude.json','utf8')));
const ctx={models:model,aptitude:apt,course:{},venue:{},technique:{}}, start='20260901',end='20260923', rates=[5,10,15,20], points=[2,3,4,6], budgets=[600,900,1200];
const rows=[]; const dt=s=>new Date(s.slice(0,4)+'-'+s.slice(4,6)+'-'+s.slice(6,8)+'T00:00:00Z'),ymd=d=>d.toISOString().slice(0,10).replaceAll('-','');
for(let d=dt(start);d<=dt(end);d=new Date(d.getTime()+86400000)){const day=ymd(d),y=day.slice(0,4),[a,b]=await Promise.all([fetch(`https://boatraceopenapi.github.io/api/v1/${y}/${day}.json`),fetch(`https://boatraceopenapi.github.io/results/v3/${y}/${day}.json`)]);if(!a.ok||!b.ok)continue;const p=await a.json(),rs=await b.json(),rm=new Map((rs.results||[]).map(x=>[`${+x.stadium_number}-${+x.number}`,x]));for(const[sid,sv]of Object.entries(p?.programs?.stadiums||{}))for(const[rn,r]of Object.entries(sv?.races||{})){const res=rm.get(`${+sid}-${+rn}`),fin=(res?.boats||[]).filter(x=>+x.racer_place_number>=1).sort((x,y)=>+x.racer_place_number-+y.racer_place_number);if(fin.length<3)continue;const combo=fin.slice(0,3).map(x=>String(x.racer_course_number)).join('-'),pr=predictionRows(ctx,r,sid,rn,day);if(pr.length!==6)continue;const ranked=pr.map(x=>+x.p?.[0]||0).sort((x,y)=>y-x),score=ranked[0]*58+(ranked[0]-ranked[1])*85,pay=res?.payouts?.trifecta||res?.payouts?.trifectas||res?.payouts?.trifecta_3||[],po=Array.isArray(pay)?pay.find(x=>String(x.combination||x.combo||x.result||'').replaceAll(' ','')===combo):null;rows.push({score,combo,yen:+(po?.amount??po?.payout??po?.payoff??0),pr})}}
rows.sort((a,b)=>b.score-a.score);const out=[];
for(const rate of rates){const xs=rows.slice(0,Math.round(rows.length*rate/100));for(const n of points)for(const budget of budgets){let hit=0,ret=0,invest=0;for(const x of xs){const bets=makeBets(x.pr,6,'hit').slice(0,n).map(z=>z.combo),unit=Math.floor(budget/n/100)*100;if(unit<100)continue;invest+=unit*n;if(bets.includes(x.combo)){hit++;ret+=x.yen*unit/100}}out.push({recommend_rate:rate,points:n,budget_per_race:budget,races:xs.length,hits:hit,hit_rate:+(100*hit/xs.length).toFixed(2),invest,return:ret,profit:ret-invest,roi:+(100*ret/invest).toFixed(2)})}}
out.sort((a,b)=>b.roi-a.roi);fs.writeFileSync(ROOT+'confidence-concentration-result.json',JSON.stringify({period:{start,end},total_races:rows.length,results:out},null,2));console.log(JSON.stringify(out.slice(0,15),null,2));

const weighted=[];
const patterns={flat:[1,1,1,1],top_heavy:[3,1,1,1],descending:[4,3,2,1],strong_top2:[3,2,1,1]};
for(const rate of [5,10,15,20]){const xs=rows.slice(0,Math.round(rows.length*rate/100));for(const [name,w] of Object.entries(patterns)){let invest=0,ret=0,hits=0;for(const x of xs){const bets=makeBets(x.pr,6,'hit').slice(0,4).map(z=>z.combo);const units=w.map(v=>v*100);invest+=units.reduce((a,b)=>a+b,0);const i=bets.indexOf(x.combo);if(i>=0){hits++;ret+=x.yen*units[i]/100}}weighted.push({recommend_rate:rate,pattern:name,races:xs.length,hits,hit_rate:+(100*hits/xs.length).toFixed(2),invest,return:ret,profit:ret-invest,roi:+(100*ret/invest).toFixed(2)})}
}
weighted.sort((a,b)=>b.roi-a.roi);
fs.writeFileSync(ROOT+'confidence-weighted-result.json',JSON.stringify({period:{start,end},note:'4-point bets with rank-based stake weighting; 100-yen units.',results:weighted},null,2));
console.log('weighted',JSON.stringify(weighted.slice(0,12),null,2));
